version: '3'

services:
  java-app:
    build:
      context: ./docker/java
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-dev}
      - MONGO_PASS=${MONGO_PASS}
    volumes:
      - .:/app
    hostname: quak
    depends_on:
      - mongo
      - kafka
  mongo:
    hostname: quak-db
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
  kafka:
    hostname: quak-kafka
    image: apache/kafka:4.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://quak-kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@quak-kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka-data:/var/lib/kafka/data
    
volumes:
  mongo-data:
  kafka-data: