server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: quak
  profiles:
    include:
    - server
    - user

  data:
    mongodb:
      host: quak-db
      port: 27017
      database: quak
      auto-index-creation: true

  kafka:
    bootstrap-servers: quak-kafka:9092    
    admin:
      auto-create: true
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable:
          idempotence: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.onyxperseus.*
logging:
  level:
    root: INFO
    com.onyxperseus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    
quak:
    kafka:
      replicas: ${KAFKA_REPLICAS:1}
      partitions: ${KAFKA_PARTITIONS:3}